apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-backend
  labels:
    app: tracker-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracker-backend
  template:
    metadata:
      labels:
        app: tracker-backend
    spec:
      containers:
      - name: tracker-backend
        image: shivanshsukhija/tracker-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
